package db <<database>> {
    object jsonserver {
      "id": 1
      "address": "The Boulevard\nMid Valley City, Lingkaran Syed Putra",
      "city": "Kuala Lumpur",
      "country": "Malaysia",
      "postalCode": "59200",
      "lng": 101.667495,
      "lat": 3.100753
    }
}

package Redux {
    package Actions {

    }

    package Reducers {

    }

    package Store {

    }
}

package React {

    package InitialState {

    }

    package View {

        object Index {

        }

        object Home
        object Map
        object List

    }

}


Reducers <-- Actions
Store <-- Reducers

InitialState <-up- Index
Index <-up- Home
Index <-up- Map
Index <-up- List

Actions <-- Map
Actions <-- List
db <-- Actions
db --> Actions
InitialState <-- Store
