package db <<database>> {
    object jsonserver {
      "id": 1
      "address": "The Boulevard\nMid Valley City, Lingkaran Syed Putra",
      "city": "Kuala Lumpur",
      "country": "Malaysia",
      "postalCode": "59200",
      "lng": 101.667495,
      "lat": 3.100753
    }
}

package Services {

    object locationsApi {
        get()
        getAll()
    }

    object groupLocations {
        getGroups()
        getUniqueGroupValues()
        filterByGroup()
    }
}

package Controllers {
    object HomeController {

    }

    object ListController {
        getAllLocations()
        locationGroups()
        uniqueGroupValues()
        filterGroup()
        reset()
    }

    object MapController {
        getAllLocations()
        locationGroups()
        uniqueGroupValues()
        filterGroup()
        reset()
    }
}

package Views {
    object home {

    }

    object list {

    }

    object map {

    }
}

jsonserver <-- locationsApi

locationsApi <-- ListController
locationsApi <-- MapController
groupLocations <-- ListController
groupLocations <-- MapController

HomeController <-- home
ListController <-- list
MapController <-- map
